[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "streamlit run app.py --server.headless true --server.address 0.0.0.0 --server.port $PORT"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
